workspace:
  base: /test
  path: site

services:
  web:
    image: fpfis/httpd-php-ci:7.1
    environment:
      - DOCUMENT_ROOT=/test/site
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome:3
    shm_size: 2g
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=800

pipeline:
  composer-install:
    group: prepare
    image: fpfis/httpd-php-ci:7.1
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress

  site-install:
    image: fpfis/httpd-php-ci:7.1
    commands:
      - ./vendor/bin/run drupal:site-install

  behat:
    group: test
    image: fpfis/httpd-php-ci:7.1
    commands:
      - ./vendor/bin/behat --strict
